### ISSUE TITLE
piOS and other text-transform theme problems

### ISSUE THREAD

**Issue by NoPlagiarism** [NoPlagiarism/friendinvites_replugged#9]
https://github.com/Saltssaumure/pios-discord-theme/blob/abd1ad7ec71032692b0022dc647da2310a3e461f/scss/part/_clyde.scss#L70

**Comment by NoPlagiarism** [comment]
Temporary fix:
```css
/* PI-OS fix for code */
code {
  text-transform: none; !important
}
```
